# Generated by Django 6.0.3 on 2026-06-11 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pagoentrenador'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiTransaccionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('wompi_id', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado'), ('VOIDED', 'Anulado'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('monto_en_centavos', models.PositiveBigIntegerField()),
                ('metodo', models.CharField(blank=True, max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wompi_transacciones', to='core.pagoentrenador')),
                ('pagador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wompi_transacciones_nomina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wompi_transacciones_nomina',
                'ordering': ['-creado'],
            },
        ),
    ]
