# Generated by Django 6.0.3 on 2026-04-04 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_equipo_entrenamiento_finanza_jugador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=1, help_text='Puntaje de 0 a 10', max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('entrenador', models.ForeignKey(limit_choices_to={'role': 'entrenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.jugador')),
            ],
            options={
                'db_table': 'evaluaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('cuota_mensual', 'Cuota Mensual'), ('inscripcion', 'Inscripción'), ('equipamiento', 'Equipamiento'), ('torneo', 'Torneo'), ('otro', 'Otro')], default='cuota_mensual', max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.jugador')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
