# Generated by Django 6.0.3 on 2026-04-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evaluacion_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='documento',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
