# Generated by Django 6.0.3 on 2026-04-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conceptopago_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=15),
        ),
    ]
