# Generated by Django 6.0.3 on 2026-04-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='finanza',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finanza', to='core.pago'),
        ),
    ]
