# Generated by Django 6.0.3 on 2026-05-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usermodel_role_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='edad_maxima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_minima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('sub10', 'Sub-10 (8 a 10 años)'), ('sub12', 'Sub-12 (11 y 12 años)'), ('sub14', 'Sub-14 (13 y 14 años)'), ('sub16', 'Sub-16 (15 y 16 años)'), ('sub18', 'Sub-18 (17 años)'), ('sub20', 'Sub-20 (18 a 20 años)')], max_length=10),
        ),
    ]
