# Generated by Django 6.0.3 on 2026-06-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_rival', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cancha', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('equipo_propio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_propios', to='core.equipo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partidos_calendario',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
