# Generated by Django 6.0.3 on 2026-06-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_partido_calendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('jugadores', models.ManyToManyField(blank=True, related_name='convocatorias', to='core.jugador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoria', to='core.partidocalendario')),
            ],
            options={
                'db_table': 'convocatorias',
            },
        ),
    ]
