# Generated by Django 6.0.3 on 2026-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_convocatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidocalendario',
            name='goles_contra',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidocalendario',
            name='goles_favor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidocalendario',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
