# Generated by Django 6.0.3 on 2026-06-02 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_partido_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjeta_amarilla', models.BooleanField(default=False)),
                ('tarjeta_roja', models.BooleanField(default=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, help_text='Calificacion de 1 a 10', max_digits=3, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_partido', to='core.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='core.partidocalendario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadisticas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estadisticas_partido',
                'ordering': ['jugador__usuario__last_name'],
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
