# Generated by Django 6.0.3 on 2026-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_estadistica_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('tecnica', 'Técnica'), ('tactica', 'Táctica'), ('fisica', 'Física')], default='tecnica', max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Puntaje de 0 a 5', max_digits=3, null=True),
        ),
    ]
