# Generated by Django 6.0.3 on 2026-06-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_evaluacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionDeportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tecnica', 'Técnica'), ('tactica', 'Táctica'), ('fisica', 'Física')], default='tecnica', max_length=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('entrenador', models.ForeignKey(limit_choices_to={'role': 'entrenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='core.jugador')),
            ],
            options={
                'db_table': 'observaciones_deportista',
                'ordering': ['-fecha'],
            },
        ),
    ]
