# Generated by Django 6.0.3 on 2026-06-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notificacion_emisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.convocatoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_convocatoria', to='core.jugador')),
            ],
            options={
                'db_table': 'respuestas_convocatoria',
                'unique_together': {('convocatoria', 'jugador')},
            },
        ),
    ]
