# Generated by Django 6.0.3 on 2026-06-08 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_respuesta_convocatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('entrenador', 'Entrenador'), ('deportista', 'Deportista'), ('acudiente', 'Acudiente'), ('pendiente', 'Pendiente')], default='deportista', max_length=20),
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='core.jugador')),
                ('usuario', models.OneToOneField(limit_choices_to={'role': 'acudiente'}, on_delete=django.db.models.deletion.CASCADE, related_name='acudiente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acudientes',
            },
        ),
    ]
